# @package paths

code_dir: /data/private/cc/experiment/MMP/UNITER
output_dirs: 
  mlflow: /data/private/cc/experiment/MMP/UNITER/results
  model: /data/private/cc/experiment/MMP/UNITER/results/exp_results