# @package _global_

configs:
  train_batch_size: 8192
  val_batch_size: 8192
  gradient_accumulation_steps: 4
  learning_rate: 8.0e-5
  num_train_steps: 4000
  valid_steps: 500
  fp16: true
  optim: adamw
  betas: [0.9, 0.98]
  weight_decay: 0.01
  dropout: 0.1
  grad_norm: 2.0
  warmup_steps: 400

mlflow:
  num_gpus: 1