defaults:
  - optional data: default
  - optional training: default

scripts:
  train_sh: /data/private/cc/experiment/MMP/UNITER/manager/scripts/train.sh
  train_py: /data/private/cc/experiment/MMP/UNITER/train_ve.py

mlflow:
  exp_name: finetune
  output_dir: /data/private/mxy/exp/UNITER/finetune
  code_dirs: ['/data/private/mxy/code/cc-UNITER/data', 
              '/data/private/mxy/code/cc-UNITER/model', 
              '/data/private/mxy/code/cc-UNITER/optim',
              '/data/private/mxy/code/cc-UNITER/utils']
  num_gpus: 1
  debug: false
  verbose: false

# disable hydra logging
hydra:
  run:
    dir: hydra
  sweep:
    dir: hydra
    subdir: .

configs:
  model_config: /data/private/cc/experiment/MMP/UNITER/config/uniter-base.json
  checkpoint: /data/private/cc/experiment/MMP/pretrained_ckpts/pretrained/uniter-base.pt
  output_dir: /data/private/mxy/exp/UNITER/finetune/vqa/fewshot/seed_${configs.data_seed}
  seed: 42



















