defaults:
  - optional data: default
  - optional training: default
  - optional paths: cc

scripts:
  train_sh: ${paths.code_dir}/manager/scripts/train.sh
  train_py: ${paths.code_dir}/train_ve.py

mlflow:
  exp_name: finetune
  output_dir: ${paths.code_dir}/results
  code_dirs: ['${paths.code_dir}/data', 
              '${paths.code_dir}/data_aug',
              '${paths.code_dir}/model', 
              '${paths.code_dir}/optim',
              '${paths.code_dir}/utils']
  num_gpus: 1
  debug: false
  verbose: false # set to true to enable std logging

# disable hydra logging
hydra:
  run:
    dir: hydra
  sweep:
    dir: hydra
    subdir: .

configs:
  model_config: ${paths.code_dir}/config/uniter-base.json
  checkpoint: /data/share/UNITER/pretrained_ckpts/pretrained/uniter-base.pt
  output_dir: ${paths.output_dir}
  seed: 42



















